### ISSUE TITLE
Börsenpreise doppelt und Werkzeug Kasten verschwindet nicht

### ISSUE THREAD

**Issue by SpeedDomains** [TheTotenkopf/SealDrop-AltisLife#1]
Hallo,

ich habe die aktuelle Version von hier. Aktuell ist es so, dass die Börsenpreise leider Doppelt angezeigt werden und das Werkzeug Kit nicht verschwindet nachdem man diese benutzt hat.

**Comment by TheTotenkopf** [comment]
Hallo,

du musst die Datenbank Tabelle "economy" einmal leeren und die Prozedur "setEconomyPrices" ausführen.

**Comment by SpeedDomains** [comment]
^Perfekt. Nun noch das Repairkit Problem, das nutze ich und dieser verschwindet aber nach der Nutzung nicht aus dem Inventar.
