### ISSUE TITLE
Checkpoint ZULU Helipad

### ISSUE THREAD

**Issue by andydigi** [TheTotenkopf/SealDrop-AltisLife#4]
Thought you might find this useful as you have a little typo for cop_air_9 on line 5469 of the mission file which actually says cop_g_9. Here is the correct version:-

init="this enableSimulation false;  this allowDamage false;  this addAction[""Helicopter Shop"",life_fnc_vehicleShopMenu,[""cop_air_1"",west,""cop_air_9"",""cop"",""APD - Kavala District""]];  this addAction[""Vehicle Garage"",  {   [[getPlayerUID player,playerSide,""Air"",player],""TON_fnc_getVehicles"",false,false] spawn life_fnc_MP;   createDialog ""Life_impound_menu"";   disableSerialization;   ctrlSetText[2802,""Fetching Vehicles....""];   life_garage_sp = ""cop_air_9""; life_garage_type = ""Air"";  },"""",0,false,false,"""",'playerSide == west'];  this addAction[""Vehicle Parking"",life_fnc_storeVehicle,"""",0,false,false,"""",'!life_garage_store'];";

Nice mod pack BTW :)

**Comment by TheTotenkopf** [comment]
WIll be fixed in the next Patch.
